name: Reusable Test
on:
  workflow_call:
    inputs:
      shard:
        type: string
        required: true
      total_shards:
        type: string
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npx vitest run --shard=${{ inputs.shard }}/${{ inputs.total_shards }}
